export const Data = [

    { name: "Mumbai" }
    , { name: "Delhi" }
    , { name: "Bengaluru" }
    , { name: "Ahmedabad" }
    , { name: "Hyderabad" }
    , { name: "Chennai" }
    , { name: "Kolkata" }
    , { name: "Pune" }
    , { name: "Jaipur" }
    , { name: "Surat" }
    , { name: "Lucknow" }
    , { name: "Kanpur" }
    , { name: "Nagpur" }
    , { name: "Patna" }
    , { name: "Indore" }
    , { name: "Thane" }
    , { name: "Bhopal" }
    , { name: "Visakhapatnam" }
    , { name: "Vadodara" }
    , { name: "Firozabad" }
    , { name: "Ludhiana" }
    , { name: "Rajkot" }
    , { name: "Agra" }
    , { name: "Siliguri" }
    , { name: "Nashik" }
    , { name: "Faridabad" }
    , { name: "Patiala" }
    , { name: "Meerut" }
    , { name: "Kalyan-Dombivali" }
    , { name: "Vasai-Virar" }
    , { name: "Varanasi" }
    , { name: "Srinagar" }
    , { name: "Dhanbad" }
    , { name: "Jodhpur" }
    , { name: "Amritsar" }
    , { name: "Raipur" }
    , { name: "Allahabad" }
    , { name: "Coimbatore" }
    , { name: "Jabalpur" }
    , { name: "Gwalior" }
    , { name: "Vijayawada" }
    , { name: "Madurai" }
    , { name: "Guwahati" }
    , { name: "Chandigarh" }
    , { name: "Hubli-Dharwad" }
    , { name: "Amroha" }
    , { name: "Moradabad" }
    , { name: "Gurgaon" }
    , { name: "Aligarh" }
    , { name: "Solapur" }
    , { name: "Ranchi" }
    , { name: "Jalandhar" }
    , { name: "Tiruchirappalli" }
    , { name: "Bhubaneswar" }
    , { name: "Salem" }
    , { name: "Warangal" }
    , { name: "Mira-Bhayandar" }
    , { name: "Thiruvananthapuram" }
    , { name: "Bhiwandi" }
    , { name: "Saharanpur" }
    , { name: "Guntur" }
    , { name: "Amravati" }
    , { name: "Bikaner" }
    , { name: "Noida" }
    , { name: "Jamshedpur" }
    , { name: "Bhilai Nagar" }
    , { name: "Cuttack" }
    , { name: "Kochi" }
    , { name: "Udaipur" }
    , { name: "Bhavnagar" }
    , { name: "Dehradun" }
    , { name: "Asansol" }
    , { name: "Nanded-Waghala" }
    , { name: "Ajmer" }
    , { name: "Jamnagar" }
    , { name: "Ujjain" }
    , { name: "Sangli" }
    , { name: "Loni" }
    , { name: "Jhansi" }
    , { name: "Pondicherry" }
    , { name: "Nellore" }
    , { name: "Jammu" }
    , { name: "Belagavi" }
    , { name: "Raurkela" }
    , { name: "Mangaluru" }
    , { name: "Tirunelveli" }
    , { name: "Malegaon" }
    , { name: "Gaya" }
    , { name: "Tiruppur" }
    , { name: "Davanagere" }
    , { name: "Kozhikode" }
    , { name: "Akola" }
    , { name: "Kurnool" }
    , { name: "Bokaro Steel City" }
    , { name: "Rajahmundry" }
    , { name: "Ballari" }
    , { name: "Agartala" }
    , { name: "Bhagalpur" }
    , { name: "Latur" }
    , { name: "Dhule" }
    , { name: "Korba" }
    , { name: "Bhilwara" }
    , { name: "Brahmapur" }
    , { name: "Mysore" }
    , { name: "Muzaffarpur" }
    , { name: "Ahmednagar" }
    , { name: "Kollam" }
    , { name: "Raghunathganj" }
    , { name: "Bilaspur" }
    , { name: "Shahjahanpur" }
    , { name: "Thrissur" }
    , { name: "Alwar" }
    , { name: "Kakinada" }
    , { name: "Nizamabad" }
    , { name: "Sagar" }
    , { name: "Tumkur" }
    , { name: "Hisar" }
    , { name: "Rohtak" }
    , { name: "Panipat" }
    , { name: "Darbhanga" }
    , { name: "Kharagpur" }
    , { name: "Aizawl" }
    , { name: "Ichalkaranji" }
    , { name: "Tirupati" }
    , { name: "Karnal" }
    , { name: "Bathinda" }
    , { name: "Rampur" }
    , { name: "Shivamogga" }
    , { name: "Ratlam" }
    , { name: "Modinagar" }
    , { name: "Durg" }
    , { name: "Shillong" }
    , { name: "Imphal" }
    , { name: "Hapur" }
    , { name: "Ranipet" }
    , { name: "Anantapur" }
    , { name: "Arrah" }
    , { name: "Karimnagar" }
    , { name: "Parbhani" }
    , { name: "Etawah" }
    , { name: "Bharatpur" }
    , { name: "Begusarai" }
    , { name: "New Delhi" }
    , { name: "Chhapra" }
    , { name: "Kadapa" }
    , { name: "Ramagundam" }
    , { name: "Pali" }
    , { name: "Satna" }
    , { name: "Vizianagaram" }
    , { name: "Katihar" }
    , { name: "Hardwar" }
    , { name: "Sonipat" }
    , { name: "Nagercoil" }
    , { name: "Thanjavur" }
    , { name: "Murwara (Katni)" }
    , { name: "Naihati" }
    , { name: "Sambhal" }
    , { name: "Nadiad" }
    , { name: "Yamunanagar" }
    , { name: "English Bazar" }
    , { name: "Eluru" }
    , { name: "Munger" }
    , { name: "Panchkula" }
    , { name: "Raayachuru" }
    , { name: "Panvel" }
    , { name: "Deoghar" }
    , { name: "Ongole" }
    , { name: "Nandyal" }
    , { name: "Morena" }
    , { name: "Bhiwani" }
    , { name: "Porbandar" }
    , { name: "Palakkad" }
    , { name: "Anand" }
    , { name: "Purnia" }
    , { name: "Baharampur" }
    , { name: "Barmer" }
    , { name: "Morvi" }
    , { name: "Orai" }
    , { name: "Bahraich" }
    , { name: "Sikar" }
    , { name: "Vellore" }
    , { name: "Singrauli" }
    , { name: "Khammam" }
    , { name: "Mahesana" }
    , { name: "Silchar" }
    , { name: "Sambalpur" }
    , { name: "Rewa" }
    , { name: "Unnao" }
    , { name: "Hugli-Chinsurah" }
    , { name: "Raiganj" }
    , { name: "Phusro" }
    , { name: "Adityapur" }
    , { name: "Alappuzha" }
    , { name: "Bahadurgarh" }
    , { name: "Machilipatnam" }
    , { name: "Rae Bareli" }
    , { name: "Jalpaiguri" }
    , { name: "Bharuch" }
    , { name: "Pathankot" }
    , { name: "Hoshiarpur" }
    , { name: "Baramula" }
    , { name: "Adoni" }
    , { name: "Jind" }
    , { name: "Tonk" }
    , { name: "Tenali" }
    , { name: "Kancheepuram" }
    , { name: "Vapi" }
    , { name: "Sirsa" }
    , { name: "Navsari" }
    , { name: "Mahbubnagar" }
    , { name: "Puri" }
    , { name: "Robertson Pet" }
    , { name: "Erode" }
    , { name: "Batala" }
    , { name: "Haldwani-cum-Kathgodam" }
    , { name: "Vidisha" }
    , { name: "Saharsa" }
    , { name: "Thanesar" }
    , { name: "Chittoor" }
    , { name: "Veraval" }
    , { name: "Lakhimpur" }
    , { name: "Sitapur" }
    , { name: "Hindupur" }
    , { name: "Santipur" }
    , { name: "Balurghat" }
    , { name: "Ganjbasoda" }
    , { name: "Moga" }
    , { name: "Proddatur" }
    , { name: "Srinagar" }
    , { name: "Medinipur" }
    , { name: "Habra" }
    , { name: "Sasaram" }
    , { name: "Hajipur" }
    , { name: "Bhuj" }
    , { name: "Shivpuri" }
    , { name: "Ranaghat" }
    , { name: "Shimla" }
    , { name: "Tiruvannamalai" }
    , { name: "Kaithal" }
    , { name: "Rajnandgaon" }
    , { name: "Godhra" }
    , { name: "Hazaribag" }
    , { name: "Bhimavaram" }
    , { name: "Mandsaur" }
    , { name: "Dibrugarh" }
    , { name: "Kolar" }
    , { name: "Bankura" }
    , { name: "Mandya" }
    , { name: "Dehri-on-Sone" }
    , { name: "Madanapalle" }
    , { name: "Malerkotla" }
    , { name: "Lalitpur" }
    , { name: "Bettiah" }
    , { name: "Pollachi" }
    , { name: "Khanna" }
    , { name: "Neemuch" }
    , { name: "Palwal" }
    , { name: "Palanpur" }
    , { name: "Guntakal" }
    , { name: "Nabadwip" }
    , { name: "Udupi" }
    , { name: "Jagdalpur" }
    , { name: "Motihari" }
    , { name: "Pilibhit" }
    , { name: "Dimapur" }
    , { name: "Mohali" }
    , { name: "Sadulpur" }
    , { name: "Rajapalayam" }
    , { name: "Dharmavaram" }
    , { name: "Kashipur" }
    , { name: "Sivakasi" }
    , { name: "Darjiling" }
    , { name: "Chikkamagaluru" }
    , { name: "Gudivada" }
    , { name: "Baleshwar Town" }
    , { name: "Mancherial" }
    , { name: "Srikakulam" }
    , { name: "Adilabad" }
    , { name: "Yavatmal" }
    , { name: "Barnala" }
    , { name: "Nagaon" }
    , { name: "Narasaraopet" }
    , { name: "Raigarh" }
    , { name: "Roorkee" }
    , { name: "Valsad" }
    , { name: "Ambikapur" }
    , { name: "Giridih" }
    , { name: "Chandausi" }
    , { name: "Purulia" }
    , { name: "Patan" }
    , { name: "Bagaha" }
    , { name: "Hardoi " }
    , { name: "Achalpur" }
    , { name: "Osmanabad" }
    , { name: "Deesa" }
    , { name: "Nandurbar" }
    , { name: "Azamgarh" }
    , { name: "Ramgarh" }
    , { name: "Firozpur" }
    , { name: "Baripada Town" }
    , { name: "Karwar" }
    , { name: "Siwan" }
    , { name: "Rajampet" }
    , { name: "Pudukkottai" }
    , { name: "Anantnag" }
    , { name: "Tadpatri" }
    , { name: "Satara" }
    , { name: "Bhadrak" }
    , { name: "Kishanganj" }
    , { name: "Suryapet" }
    , { name: "Wardha" }
    , { name: "Ranebennuru" }
    , { name: "Amreli" }
    , { name: "Neyveli (TS)" }
    , { name: "Jamalpur" }
    , { name: "Marmagao" }
    , { name: "Udgir" }
    , { name: "Tadepalligudem" }
    , { name: "Nagapattinam" }
    , { name: "Buxar" }
    , { name: "Aurangabad" }
    , { name: "Jehanabad" }
    , { name: "Phagwara" }
    , { name: "Khair" }
    , { name: "Sawai Madhopur" }
    , { name: "Kapurthala" }
    , { name: "Chilakaluripet" }
    , { name: "Aurangabad" }
    , { name: "Malappuram" }
    , { name: "Rewari" }
    , { name: "Nagaur" }
    , { name: "Sultanpur" }
    , { name: "Nagda" }
    , { name: "Port Blair" }
    , { name: "Lakhisarai" }
    , { name: "Panaji" }
    , { name: "Tinsukia" }
    , { name: "Itarsi" }
    , { name: "Kohima" }
    , { name: "Balangir" }
    , { name: "Nawada" }
    , { name: "Jharsuguda" }
    , { name: "Jagtial" }
    , { name: "Viluppuram" }
    , { name: "Amalner" }
    , { name: "Zirakpur" }
    , { name: "Tanda" }
    , { name: "Tiruchengode" }
    , { name: "Nagina" }
    , { name: "Yemmiganur" }
    , { name: "Vaniyambadi" }
    , { name: "Sarni" }
    , { name: "Theni Allinagaram" }
    , { name: "Margao" }
    , { name: "Akot" }
    , { name: "Sehore" }
    , { name: "Mhow Cantonment" }
    , { name: "Kot Kapura" }
    , { name: "Makrana" }
    , { name: "Pandharpur" }
    , { name: "Miryalaguda" }
    , { name: "Shamli" }
    , { name: "Seoni" }
    , { name: "Ranibennur" }
    , { name: "Kadiri" }
    , { name: "Shrirampur" }
    , { name: "Rudrapur" }
    , { name: "Parli" }
    , { name: "Najibabad" }
    , { name: "Nirmal" }
    , { name: "Udhagamandalam" }
    , { name: "Shikohabad" }
    , { name: "Jhumri Tilaiya" }
    , { name: "Aruppukkottai" }
    , { name: "Ponnani" }
    , { name: "Jamui" }
    , { name: "Sitamarhi" }
    , { name: "Chirala" }
    , { name: "Anjar" }
    , { name: "Karaikal" }
    , { name: "Hansi" }
    , { name: "Anakapalle" }
    , { name: "Mahasamund" }
    , { name: "Faridkot" }
    , { name: "Saunda" }
    , { name: "Dhoraji" }
    , { name: "Paramakudi" }
    , { name: "Balaghat" }
    , { name: "Sujangarh" }
    , { name: "Khambhat" }
    , { name: "Muktsar" }
    , { name: "Rajpura" }
    , { name: "Kavali" }
    , { name: "Dhamtari" }
    , { name: "Ashok Nagar" }
    , { name: "Sardarshahar" }
    , { name: "Mahuva" }
    , { name: "Bargarh" }
    , { name: "Kamareddy" }
    , { name: "Sahibganj" }
    , { name: "Kothagudem" }
    , { name: "Ramanagaram" }
    , { name: "Gokak" }
    , { name: "Tikamgarh" }
    , { name: "Araria" }
    , { name: "Rishikesh" }
    , { name: "Shahdol" }
    , { name: "Medininagar (Daltonganj)" }
    , { name: "Arakkonam" }
    , { name: "Washim" }
    , { name: "Sangrur" }
    , { name: "Bodhan" }
    , { name: "Fazilka" }
    , { name: "Palacole" }
    , { name: "Keshod" }
    , { name: "Sullurpeta" }
    , { name: "Wadhwan" }
    , { name: "Gurdaspur" }
    , { name: "Vatakara" }
    , { name: "Tura" }
    , { name: "Narnaul" }
    , { name: "Kharar" }
    , { name: "Yadgir" }
    , { name: "Ambejogai" }
    , { name: "Ankleshwar" }
    , { name: "Savarkundla" }
    , { name: "Paradip" }
    , { name: "Virudhachalam" }
    , { name: "Kanhangad" }
    , { name: "Kadi" }
    , { name: "Srivilliputhur" }
    , { name: "Gobindgarh" }
    , { name: "Tindivanam" }
    , { name: "Mansa" }
    , { name: "Taliparamba" }
    , { name: "Manmad" }
    , { name: "Tanuku" }
    , { name: "Rayachoti" }
    , { name: "Virudhunagar" }
    , { name: "Koyilandy" }
    , { name: "Jorhat" }
    , { name: "Karur" }
    , { name: "Valparai" }
    , { name: "Srikalahasti" }
    , { name: "Neyyattinkara" }
    , { name: "Bapatla" }
    , { name: "Fatehabad" }
    , { name: "Malout" }
    , { name: "Sankarankovil" }
    , { name: "Tenkasi" }
    , { name: "Ratnagiri" }
    , { name: "Rabkavi Banhatti" }
    , { name: "Sikandrabad" }
    , { name: "Chaibasa" }
    , { name: "Chirmiri" }
    , { name: "Palwancha" }
    , { name: "Bhawanipatna" }
    , { name: "Kayamkulam" }
    , { name: "Pithampur" }
    , { name: "Nabha" }
    , { name: "Shahabad, Hardoi" }
    , { name: "Dhenkanal" }
    , { name: "Uran Islampur" }
    , { name: "Gopalganj" }
    , { name: "Bongaigaon City" }
    , { name: "Palani" }
    , { name: "Pusad" }
    , { name: "Sopore" }
    , { name: "Pilkhuwa" }
    , { name: "Tarn Taran" }
    , { name: "Renukoot" }
    , { name: "Mandamarri" }
    , { name: "Shahabad" }
    , { name: "Barbil" }
    , { name: "Koratla" }
    , { name: "Madhubani" }
    , { name: "Arambagh" }
    , { name: "Gohana" }
    , { name: "Ladnu" }
    , { name: "Pattukkottai" }
    , { name: "Sirsi" }
    , { name: "Sircilla" }
    , { name: "Tamluk" }
    , { name: "Jagraon" }
    , { name: "AlipurdUrban Agglomerationr" }
    , { name: "Alirajpur" }
    , { name: "Tandur" }
    , { name: "Naidupet" }
    , { name: "Tirupathur" }
    , { name: "Tohana" }
    , { name: "Ratangarh" }
    , { name: "Dhubri" }
    , { name: "Masaurhi" }
    , { name: "Visnagar" }
    , { name: "Vrindavan" }
    , { name: "Nokha" }
    , { name: "Nagari" }
    , { name: "Narwana" }
    , { name: "Ramanathapuram" }
    , { name: "Ujhani" }
    , { name: "Samastipur" }
    , { name: "Laharpur" }
    , { name: "Sangamner" }
    , { name: "Nimbahera" }
    , { name: "Siddipet" }
    , { name: "Suri" }
    , { name: "Diphu" }
    , { name: "Jhargram" }
    , { name: "Shirpur-Warwade" }
    , { name: "Tilhar" }
    , { name: "Sindhnur" }
    , { name: "Udumalaipettai" }
    , { name: "Malkapur" }
    , { name: "Wanaparthy" }
    , { name: "Gudur" }
    , { name: "Kendujhar" }
    , { name: "Mandla" }
    , { name: "Mandi" }
    , { name: "Nedumangad" }
    , { name: "North Lakhimpur" }
    , { name: "Vinukonda" }
    , { name: "Tiptur" }
    , { name: "Gobichettipalayam" }
    , { name: "Sunabeda" }
    , { name: "Wani" }
    , { name: "Upleta" }
    , { name: "Narasapuram" }
    , { name: "Nuzvid" }
    , { name: "Tezpur" }
    , { name: "Una" }
    , { name: "Markapur" }
    , { name: "Sheopur" }
    , { name: "Thiruvarur" }
    , { name: "Sidhpur" }
    , { name: "Sahaswan" }
    , { name: "Suratgarh" }
    , { name: "Shajapur" }
    , { name: "Rayagada" }
    , { name: "Lonavla" }
    , { name: "Ponnur" }
    , { name: "Kagaznagar" }
    , { name: "Gadwal" }
    , { name: "Bhatapara" }
    , { name: "Kandukur" }
    , { name: "Sangareddy" }
    , { name: "Unjha" }
    , { name: "Lunglei" }
    , { name: "Karimganj" }
    , { name: "Kannur" }
    , { name: "Bobbili" }
    , { name: "Mokameh" }
    , { name: "Talegaon Dabhade" }
    , { name: "Anjangaon" }
    , { name: "Mangrol" }
    , { name: "Sunam" }
    , { name: "Gangarampur" }
    , { name: "Thiruvallur" }
    , { name: "Tirur" }
    , { name: "Rath" }
    , { name: "Jatani" }
    , { name: "Viramgam" }
    , { name: "Rajsamand" }
    , { name: "Yanam" }
    , { name: "Kottayam" }
    , { name: "Panruti" }


] 